import { ALCHEMY_API_KEY } from '../secrets';

export const chains = {
  eth: { chainId: 1, rpc: 'https://rpc.ankr.com/eth' },
  ropsten: { chainId: 3, rpc: '' },
  rinkeby: { chainId: 4, rpc: '' },
  goerli: {
    chainId: 5,
    rpc: `https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}`,
  },
  optimisticEthereum: { chainId: 10, rpc: '' },
  kovan: { chainId: 42, rpc: '' },
  bsc: { chainId: 56, rpc: 'https://rpc.ankr.com/bsc' },
  sokol: { chainId: 77, rpc: '' },
  bscTestnet: { chainId: 97, rpc: 'https://rpc.ankr.com/bsc_testnet_chapel' },
  xdai: { chainId: 100, rpc: '' },
  gnosis: { chainId: 100, rpc: 'https://rpc.ankr.com/gnosis' },
  heco: { chainId: 128, rpc: '' },
  polygon: { chainId: 137, rpc: 'https://rpc.ankr.com/polygon' },
  opera: { chainId: 250, rpc: '' },
  hecoTestnet: { chainId: 256, rpc: '' },
  optimisticGoerli: { chainId: 420, rpc: '' },
  moonbeam: { chainId: 1284, rpc: '' },
  moonriver: { chainId: 1285, rpc: '' },
  moonbaseAlpha: { chainId: 1287, rpc: '' },
  fantom: { chainId: 250, rpc: 'https://rpc.ankr.com/fantom' },
  ftmTestnet: { chainId: 4002, rpc: 'https://rpc.ankr.com/fantom_testnet' },
  chiado: { chainId: 10200, rpc: '' },
  arbitrumOne: { chainId: 42161, rpc: '' },
  avalancheFujiTestnet: { chainId: 43113, rpc: '' },
  avalanche: { chainId: 43114, rpc: 'https://rpc.ankr.com/avalanche' },
  polygonMumbai: { chainId: 80001, rpc: 'https://rpc.ankr.com/polygon_mumbai' },
  arbitrumTestnet: { chainId: 421611, rpc: '' },
  arbitrumGoerli: { chainId: 421613, rpc: '' },
  sepolia: { chainId: 11155111, rpc: '' },
  aurora: { chainId: 1313161554, rpc: '' },
  auroraTestnet: { chainId: 1313161555, rpc: '' },
  harmony: { chainId: 1666600000, rpc: 'https://rpc.ankr.com/harmony' },
  harmonyTest: { chainId: 1666700000, rpc: '' },
  cronosTestnet: { chainId: 338, rpc: 'https://evm-t3.cronos.org/' },
  cronos: { chainId: 25, rpc: 'https://evm.cronos.org' },
  celo: { chainId: 42220, rpc: 'https://rpc.ankr.com/celo' },
  arbitrum: { chainId: 42161, rpc: 'https://arb1.arbitrum.io/rpc' },
};
